services:
  web:
    image: exomed-fe
    container_name: exomed-fe
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5174}
    ports:
      - "5173:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
